### ISSUE TITLE
Python bindings for cross-platform Topologic

### ISSUE THREAD

**Issue by Moult** [NonManifoldTopology/Topologic#15]
I saw in a demonstration a snippet of Python that had an `import topologic` in Dynamo. This suggests that somewhere, there exists Python bindings. Where can I find this code?

In addition, has Topologic been compiled for Linux?

**Comment by wassimj** [comment]
Hi Dion,

 

Thanks again for inviting me to give this talk. I hope your group found it useful.

If you download and install Dynamo for Grasshopper, you will get a TopologicNET.dll that loads very well into python.

 

http://topologic.app

 

Bets Regards,

 

Wassim

**Comment by wassimj** [comment]
The effort to create a python module is well underway.
