### ISSUE TITLE
Bug: Topologic Grasshopper, Transfer Dictionary True Causes Crash

### ISSUE THREAD

**Issue by NGimbal** [NonManifoldTopology/Topologic#25]
## Your Environment

* Library used: Topologic Grasshopper
* Host application and version (if any) Rhino 6 & Rhino 7, Tested minimal script below in both platforms
* Operating System and version (desktop or mobile): Windows 10

## Context

I would like to divide topology while transferring the dictionary to provide a cascading dictionary from an envelope to levels, then from levels to rooms.

## Expected Behavior

Topology.Divide with Transfer Dictionary should give dictionary of parent to all children

## Current Behavior

Grasshopper / Rhino 6 & 7 crashes without warning.

## Steps to Reproduce

Minimal script that causes crash
<img width="1350" alt="Screen Shot 2021-04-03 at 8 52 03 PM" src="https://user-images.githubusercontent.com/34066664/113495346-1eb86f00-94bf-11eb-9146-5ad3d57d5fba.png">

Thanks for all the work that's gone into Topologic! I saw the yourdeskuniversity presentation last week and was really blown away. I've been playing with Topologic Grasshopper for the few days since. Just want to put this here, in case it would be helpful at all. 

If you all want to point out any strategies, work arounds or misconceptions I might have that would be greatly appreciated!

**Comment by wassimj** [comment]
Thank you for kind words. Sorry, “Divide” is the wrong method and is not used because it is buggy. Use Slice instead. The two resulting cells will inherit the dictionary of the parent. Further slicing will do the same.

**Comment by NGimbal** [comment]
Thanks @wassimj !
