### ISSUE TITLE
If I want to understand the principle.

### ISSUE THREAD

**Issue by HongLouyemeng** [NonManifoldTopology/Topologic#28]
If I want to understand the principle，Do you have any textbooks or directions to recommend？

**Comment by wassimj** [comment]
Take a look at our publications listed on https://topologic.app

**Comment by HongLouyemeng** [comment]
> 看看我们在[https://topologic.app 上](https://topologic.app)列出的出版物[](https://topologic.app)



> Take a look at our publications listed on https://topologic.app

It's amazing

**Comment by HongLouyemeng** [comment]
> Take a look at our publications listed on https://topologic.app

It's amazing.
