### ISSUE TITLE
Bug Topology.AddApertures

### ISSUE THREAD

**Issue by michalinadengusiak** [NonManifoldTopology/Topologic#29]
## Your Environment

* Host application and version (if any): Rhino 7 
* Operating System and version (desktop or mobile): Windows

## Context

I was following the 2nd tutorial on Topologic and decided to add apertures. 

## Expected Behavior

There should be apertures on the building. 

## Current Behavior

There are no apertures on the building.

## Steps to Reproduce

1. I connected Topology.AddApertures to a building.
2. Under Aperture Topologies I connected the Topology of the geometry, I wanted as my apertures.

This is the GH definition:

[AddApertures_Bug.zip](https://github.com/NonManifoldTopology/Topologic/files/9314493/AddApertures_Bug.zip)

## Possible Solution

Unfortunately, I don't have an idea, as to what might have caused the problem...

**Comment by wassimj** [comment]
Can you please screen shot your definition and post it here as an image? Thanks

**Comment by michalinadengusiak** [comment]
This is the definition:
![image](https://user-images.githubusercontent.com/37042279/184312258-3d60d2eb-316e-49f4-ada7-543d0abdaa2f.png)

**Comment by wassimj** [comment]
I see the mistake. When you add Apertures to a topology like a CellComplex (e.g. a building), the Apertures are added to the corresponding Faces of the CellComplex not to the CellComplex itself. So, to get the apertures back, you need to first get the Faces of the CellComplex and then connect that to Topology.Apertures. Some faces (e.g. floors, ceilings, roofs) will not have apertures.

**Comment by wassimj** [comment]
Also, under normal circumstances (a 3D building with Apertures being windows and doors), your Aperture topology should be a Face not a Wire.

**Comment by michalinadengusiak** [comment]
Thank you so much for helping me and replying so quickly! Sorry, about the mix-up, but now I know for the future and will keep it in mind. 😊😉

**Comment by wassimj** [comment]
Excellent! Glad it was solved! You should try Topologic in Blender. It is sooo much more powerful than Grasshopper (and Free forever!)
